# Generated by Django 4.1.7 on 2023-03-01 13:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_django', '0004_postlike_postcomment'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='postcomment',
            options={'ordering': ('-date',), 'verbose_name': 'Comment', 'verbose_name_plural': 'Comment'},
        ),
    ]
