# Generated by Django 4.1.7 on 2023-03-01 13:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_django', '0005_alter_postcomment_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ('-title',), 'verbose_name': 'Post', 'verbose_name_plural': 'Posts'},
        ),
    ]
